# Generated by Django 4.0.8 on 2023-11-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseallocation',
            old_name='lecturer',
            new_name='instructor',
        ),
    ]
