# Generated by Django 3.2.1 on 2023-11-26 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_choice_id_alter_progress_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pass_mark',
            field=models.SmallIntegerField(blank=True, default=50, help_text='Percentage required to pass.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Pass Mark'),
        ),
    ]
